
import Masonry from "react-masonry-css";
import Layout from "components/layout";
import Link from "next/link";
import { Book, Video, Zap, User } from "react-feather";


export default () => {
  return (
    <Layout>
      <div className="flex">
        <div className="pl-18 lg:pl-32 w-full leading-relaxed">
          <h1 className="text-5xl font-bold mb-12">
            <span className="text-primary">Reality: </span>A controlled hallucination?  
          </h1>
<p>
And if so, can we simulate our conscious reality?
In common colloquial usage, the word ‘reality’ refers to the status of objects, time,
space, phenomena, all that is known and all that is unknown around us. Yet
philosophers, physicists and sociologists of the last centuries and even millennials
have argued that reality is not an absolute entity. Since, numerous theories have
tried to grasp what reality signifies and implies.
As neuroscience and the understanding of brain and consciousness have seen
immense progress in the last decades, our understanding of reality has been
challenged more than ever. Neuroscientist explain that reality is generated by the
activity of countless neurons in the brain shaping our conscious experience. The
brain inside our protecting skulls can not see, it can not smell, it is not exposed to
light, colours or pressure. Instead, it fully relies on sensory information being
translated into electrical signals which travel along our nerves before being
processed in the brain. In addition to that, neuroscientists have discovered a process
interfering with the processing of sensory information, indicating that our perception
of reality relies on more than just a stream of frequency-coded electrical signals.
Numerous experiments have shown, that the brain integrates pre-existing beliefs and
predictions into the interpretation of sensory signals. In a process of 'informed
guesswork', the brain actively generates our conscious environment rather than
passively perceiving it (Lehar, S., 2011). Our ‘reality’ is highly influenced by our
perceptual predictions, suggesting that reality is not absolute and might differ from
person to person according to individual preexisting beliefs and experiences. A
logical implication of this scientific framework is that subjective reality can, thus, be
altered by changing intrinsic beliefs and predictions a person has. This further
contributes to the epistemological dualism between direct (naïve) realism claiming
that sensory information provides us with an accurate depiction of reality as it really is
and indirect (representational) realism which supports the notion that our neural
processes generate a perceptual interpretation of reality.
Consequently, this significantly impacts the reliability of what we think is real.
Disease such as Schizophrenia, Bonnet’s disease and many more have shown to
distort patients’ perception of reality and at times produce hallucinations (Thomson,
A., 2006) These delusions are in most cases impossible to consciously distinguish
from real experiences, just as we very rarely realise, that we are dreaming. In terms
of neuroscience, the reality of a hallucinating person is partly constructed without
external stimulus. It is a perception that is generated by defects or anomalies in
neural function and is beyond the brain’s normal control over the interpretation of
sensory stimuli. A hallucination leads to incoherence between the reality of affected
individuals and ‘healthy’ individuals, emphasizing the relative nature of the word
‘reality’. Logically, the implication of this is, that reality might be considered a form of
hallucination, but one most people agree on as most people have similar experiences
and beliefs and, thus, perceptual predictions. Similar perceptual predictions and
same sensory stimuli result in similar 'best guesses' over what reality is. As soon as
one’s reality significantly deviates from the reality commonly agreed on, we start to
look for what has interfered with the reality 'creating' process in this specific individual
that lead to a different final result.

So if our conscious experience of reality is an interpreted virtual copy of the outside
world, as the theory suggests, this could give rise to the possibility of simulating a
reality indistinguishable from the ‘true base reality' by imitating or interfering with the
neural conscious-reality generating process in humans, once technological maturity
is achieved. The question of whether this technological breakthrough will ever be
reached is highly debated.
By introducing the concept of an evil demon that represents a complete illusion of the
external world, Réné Descartes was one of the first western philosopher expressing
ideas in favor of the necessity to doubt the reliability of our senses in the reality
generating process considering the probability of our perceptual reality being a
simulated illusion (Cottingham, J., 1996). The contemporary equivalent of this
analogy is the brain in a vat scenario by Gilbert Harman. This thought experiment
enlarged on the concept of generating a simulated reality by stimulating a brain,
separated from the body and conserved in life-sustaining liquid, with appropriate
electrical stimuli similar to those the brain would receive normally. The brain cannot
know where it is as it fully relies on the sensory signals it receives from the ‘machine’,
that in this experiment, are manipulated and controlled (Thompson, E., 2011).
Modern technology of virtual reality already provides users with highly advanced
visual and auditory stimuli. Further technological advances could mimic sensations of
dimensions like touch and taste and the ease of distinguishing ‘true’ reality from
virtual, simulated virtuality could gradually decrease until technology makes them
indistinguishable (Solon, O., 2016).
This thought experiment is a crucial element of philosophical scepticism and
solipsism stating that one can only be sure of the existence of the own mind (Cogito
ergo sum). It is, thus, epistemologically impossible to tell whether we are part of a
simulated reality or we perceive the ‘true’ reality. Finding evidence would pose an
infinite regress problem as the evidence would be part of the simulation as well and
would, therefore, not be valid.
So what does that mean? One thing that can be said with certainty is, that nothing is
certain. Every scientific theory can be experimentally proven until its probability of
being true is high enough to consider it ‘true’, but no theory, hypothesis or
observation can be said to be absolutely true. We can only approximate certainty and
can not postulate dogmata of perpetual validity. The existence of the moon has been
experimentally proven innumerable times, humans have even walked on its surface,
yet it cannot be stated with absolute certainty that the moon is still there when we
look away. There is no fundamental truth, especially not for the existence of our
environment and the things we believe to be real. By conducting experiments and
empirical research, we can only increase the probability of something being true.
Nothing is certain and nothing is impossible (Hut, P., Alford, P., Tegmark, M., 2006)
So how does this inaccurate portrayal of the real world make sense from an
evolutionary perspective? Mathematical physicist Cetah Prakash explains that
organisms that perceive the world around them much more accurately, would not
necessarily be more fit than organisms whose perception of reality is tuned to their
fitness. In fact, they would probably be less well suited to their environment. The
pathway constructing our inner portrayal of our surroundings evolved to best fit the
organism’s individual needs and doesn’t aim to depict our surroundings more and
more accurately. Animals living in caves or other environments where light is absent,
for example, often lose their ability to see and monitor light, significantly impacting
their perception of reality. The loss or absence of vision decreases unnecessary

energy expenditure and, thereby, increasing the fitness of this particular organism.
Some substances smell bad to humans but give a pleasant sensation to other
organisms, creating a significant disagreement in the perceptions between both
organisms. For humans, this substance might be toxic but beneficial for the other
organism, showing how well our perception is tuned to our individual fitness.
But if perception varies in different individuals and organisms and eventually even
within the same person over time, does it mean, that there is no absolute reality? If a
tree falls in the forest and no one is around to hear it, does it make a sound? If there
is no ear to hear it, there is no sound. The physical implications such as the vibration
of air at a certain frequency will happen, yet as there is nobody with a structure
suitable to hear it, no sound would be perceived. Perceptual interpretations might
vary, but underlying physical interactions take place consistently. This leads onto the
position of scientific realism: it states that the universe obeys laws of physics
independent of the observer. Even statements on unobservable phenomena can be
made. Science is progressive and can predict. The aggregation of physical
interactions builds a fundament that is shaped into individual, relative reality,
dependent on idiosyncratic adaptations and characteristics of the observer.
Cottingham, J., (1996). René Descartes: Meditations on First Philosophy with Selections from the
Objections and Replies. Cambridge: Cambridge University Press
Zbigniew J., (2000). Cartesian Theodicy: Descartes' Quest for Certitude. Springer. pp. 62–68
Thompson, E.,: Cosmelli, Diego (2011). “Brain in a Vat or Body in a World? Brainbound versus enactive
views of experience”. Philosophical Topics. 39 (1): 163-180
Bostrom, N., (2003). „are you living in a computer simulation?” Philosophical Quarterly. 53 (211): 243–255.
Lehar, S., (2000). The Function of Conscious Experience: An Analogical Paradigm of Perception and
Behaviour , Consciousness and Cognition.
Popkin, R,, (2003). The history of skepticism: from Savonarola to Bayle. Popkin, Richard Henry, 1923-
(Rev. and expanded ed.). Oxford: Oxford University Press.
Thompson, A., (2006). “Hearing Voices: Some People Like It”. LiveScience.com
Solon, O., (2016): Is our world a simulation? Available at:
https://www.theguardian.com/technology/2016/oct/11/simulated-world-elon-musk-the-matrix, [accessed on
the 2nd of March, 2019]
Hut, P., Alford, M., Tegmark, M. (2006). "On Math, Matter and Mind". Foundations of Physics. 36: 765–794
</p>
        </div>
      </div>
    </Layout>
  );
};
